"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const retrieveUsers_controller_1 = require("./../controller/retrieveUsers.controller");
const loginUser_controller_1 = require("./../controller/loginUser.controller");
const createPlaylist_controller_1 = require("./../controller/createPlaylist.controller");
const validateShape_middleware_1 = require("../middlewares/validateShape.middleware");
const createPlaylist_shape_1 = require("./../shapes/createPlaylist.shape");
const verifyAuthenticatedUser_middleware_1 = require("./../middlewares/verifyAuthenticatedUser.middleware");
const verifyRequestUser_middleware_1 = require("./../middlewares/verifyRequestUser.middleware");
const express_1 = require("express");
const createUser_controller_1 = require("./../controller/createUser.controller");
const verifyDuplicateUser_middleware_1 = require("../middlewares/verifyDuplicateUser.middleware");
const router = (0, express_1.Router)();
exports.router = router;
router.post("/register", verifyRequestUser_middleware_1.verifyRequestUserMiddleware, verifyDuplicateUser_middleware_1.verifyDuplicateUserMiddleware, createUser_controller_1.createUserController);
router.post("/login", verifyRequestUser_middleware_1.verifyRequestUserMiddleware, loginUser_controller_1.loginUserController);
router.put("/playlist", (0, validateShape_middleware_1.validateShapeMiddleware)(createPlaylist_shape_1.createPlaylistShape), verifyAuthenticatedUser_middleware_1.verifyAuthenticatedUserMiddleware, createPlaylist_controller_1.createPlaylistController);
router.delete("/playlist", verifyAuthenticatedUser_middleware_1.verifyAuthenticatedUserMiddleware, createPlaylist_controller_1.createPlaylistController);
router.get("/", verifyAuthenticatedUser_middleware_1.verifyAuthenticatedUserMiddleware, retrieveUsers_controller_1.retrieveUsersController);
